avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

social:
  - name: GitHub
    link: https://github.com/JavaZeroo
    icon: ri:github-line
    color: '#181717'
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/95945127
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: Telegram
    link: https://t.me/javaisme0
    icon: ri:telegram-line
    color: '#0088CC'

banner:
  enable: true
  title: Javaä¸åŠ ç³–çš„Blog
  border: false
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

font:
  cdn:
    enable: true
    lib:
      - https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@900&display=swap
  serif:
    family: '''Noto Sans SC'', STZhongsong, STKaiti, KaiTi, Roboto, serif'
    weight: 900
  sans_serif:
    family: '''Noto Sans SC'', ''PingFang SC'', ''Microsoft YaHei'', Roboto, Arial, sans-serif'
    weight: 400
  monospace:
    family: '''Noto Sans SC'', ''Source Code Pro'', ''Courier New'', Courier, Consolas, Monaco, monospace'

head:
  css:
    fonts: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@900&display=swap

fireworks:
  enable: false
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'


codeblock:
  copy_btn: true


creative_commons:
  license: by-Jimmy
  post: true
  language: deed.zh
  clipboard: false


footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'


footer:
  powered:
    enable: false

footer:
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²é»˜é»˜åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2022-08-25T00:00:00'


google_analytics:
  enable: true
  id: G-NDVPJNZY7Q


google_adsense:
  enable: false

tags: 
  æ·±åº¦å­¦ä¹ : bulb-on-solid