format = '''
$os$status$directory$package$git_branch$git_status$conda$time
ğŸ’«'''

scan_timeout = 10


[os]
format = "[$symbol]($style)"
style = "dimmed white"
disabled = false # Disabled by default

[os.symbols]
Ubuntu = "ïŒ› "
Windows = "ï¡± "



[conda]
format = '[$symbol$environment](green) '
symbol = "ï„Œ "
ignore_base = false


[directory]
truncation_length = 20
truncation_symbol = 'â€¦/'
read_only = " ï ½"


[docker_context]
symbol = "ïŒˆ "


[git_branch]
symbol = "ï˜ "


[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '


[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[status]
symbol = 'ğŸ”´ '
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false
